language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
git:
  depth: false
branches:
  only:
  - master
before_install:
- npm install -g npm@latest
install:
- npm install --silent
script:
- curl https://us-central1-cinelah-92dbb.cloudfunctions.net/scrapeShowtimes
notifications:
  email: false
